jobs:
  - name: job-1
    public: true
    plan:
      - task: task-01
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu, tag: latest}
          run:
            path: cat
            args: [/etc/os-release]
      - task: task-02
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: centos, tag: latest}
          run:
            path: cat
            args: [/etc/os-release]
