resources:
- name: sample-git-repo-main
  type: git
  source:
    uri: https://github.com/rkal8996/concourse-test-code.git
    branch: main

jobs:
- name: job-execute-task-from-git-file
  public: true
  plan:
  - get: sample-git-repo-main
  - task: task-01-print-hello-world
    file: sample-git-repo-main/simple-tasks/hello-world-task.yaml
  - task: task-02-print-directories
    file: sample-git-repo-main/simple-tasks/print-directories.yaml
  - task: task-03-system-info
    file: sample-git-repo-main/simple-tasks/system-info.yaml