resources:
- name: sample-git-repo-main
  type: git
  source:
    uri: https://github.com/rkal8996/concourse-test-code.git
    branch: main
  check_every: 1s
- name: my-timer
  type: time
  source:
    interval: 5s

jobs:
- name: job-execute-task-from-git-file
  public: true
  plan:
  - get: sample-git-repo-main
    trigger: true
  - task: task-01-print-hello-world
    file: sample-git-repo-main/simple-tasks/hello-world-task.yaml
- name: job-execute-task-from-git-file-print-dir
  public: true
  plan:
  - get: sample-git-repo-main
    trigger: true
  - task: task-02-print-directories
    file: sample-git-repo-main/simple-tasks/print-directories.yaml
- name: job-execute-task-from-git-get-sys-info
  public: true
  plan:
  - get: sample-git-repo-main
    trigger: true
  - get: my-timer
    trigger: true
  - task: task-03-system-info
    file: sample-git-repo-main/simple-tasks/system-info.yaml